services:
  - type: web
    name: tgbot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python fsm_bot_verified_access_controlled.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12